name: NodeJS with Webpack

on:
  workflow_run:
      workflows: [run-unit-tests]
      branches: [main]
      types:
        - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Build
      run: |
        cd platform
        npm install
        npm run build -- --env tokenServerUrl=http://example.com:1234
        npm run package
    - name: Upload Github Pages artifact
      uses: actions/upload-pages-artifact@v2.0.0
      with:
        path: platform/dist
